export const routes = [
  "/",
  "/solutions/security",
  "/guard-marketplace",
  "/radios-equipment",
  "/guard-patrol-software",
  "/guard-attendance-software",
  "/ptt-radio-rental",
  "/pricing",
  "/contact",
  "/get-started",
  "/guards",
  "/guards/join",
  "/join/sales",
  "/security-trust",
  "/privacy",
  "/popia",
  "/terms",
] as const;

export const legacyRedirects: Array<[string, string]> = [
  ["/connectivity", "/radios-equipment"],
  ["/connectivity/anything/else", "/radios-equipment"],
  ["/devices", "/radios-equipment"],
  ["/devices/abc", "/radios-equipment"],
  ["/platforms", "/"],
  ["/platforms/aiot-management", "/"],
  ["/platforms/push-to-talk", "/radios-equipment"],
  ["/solutions", "/solutions/security"],
  ["/solutions/agriculture", "/solutions/security"],
  ["/solutions/construction", "/solutions/security"],
  ["/solutions/logistics", "/solutions/security"],
  ["/solutions/public-safety", "/solutions/security"],
  ["/solutions/utilities", "/solutions/security"],
  ["/systems", "/"],
  ["/marketplace", "/guard-marketplace"],
  ["/partners", "/contact"],
];
